package dev.elsebase.template;

import java.util.*;
import java.util.function.BiFunction;
import net.minecraft.core.Direction;

/** Approved whole-block room designs. Horizontal patterns rotate one quadrant, including directed materials. */
public final class BuiltinThemes {
    public static Theme create(String id,String name) {
        if(!List.of(TemplateState.THEMES).contains(id)) throw new IllegalArgumentException("Unknown built-in theme: "+id);
        return new Theme(name,"Elsebase",grid(name,14,7,(u,v) -> wall(id,u,v)),square(name,(x,z) -> floor(id,x,z)),square(name,(x,z) -> ceiling(id,x,z)));
    }
    private static Pattern.Material block(String id) { return new Pattern.Material("minecraft:"+id,Map.of()); }
    private static Pattern.Material directed(String id,String key,String value) { return new Pattern.Material("minecraft:"+id,Map.of(key,value)); }
    private static Pattern.Material log(String id,String axis) { return directed(id,"axis",axis); }
    private static boolean column(int u) { return u==0 || u==6 || u==7 || u==13; }
    private static boolean band(int v) { return v==0 || v==3 || v==6; }

    private static Pattern.Material wall(String id,int u,int v) {
        boolean post=column(u),rail=band(v); int local=u<7?u:13-u;
        return switch(id) {
            case "quiet_workshop" -> post?log("stripped_spruce_log",rail?"z":"y"):rail?log("stripped_spruce_log","x")
                    :block(local==3 && v==2?"waxed_cut_copper":v==1 || v==4?"stone_bricks":"polished_andesite");
            case "arcane_archive" -> post?log("dark_oak_log",rail?"z":"y"):rail?log("dark_oak_log","x")
                    :block(local==1?"gilded_blackstone":local==2?"purple_terracotta":local==3 || local==4?"bookshelf":"stone_bricks");
            case "verdant_cloister" -> post?log(v==3?"stripped_birch_log":"oak_log",v==3?"z":"y")
                    :block(v==0?"mud_bricks":v==3?"chiseled_stone_bricks":v==6?"oak_planks":"mossy_stone_bricks");
            case "astral_observatory" -> block(post?(v==0 || v==3 || v==6?"chiseled_quartz_block":"quartz_pillar")
                    :local==3?"blue_terracotta":local==2 && (v==2 || v==4)?"amethyst_block":"polished_blackstone_bricks");
            case "porcelain_sanctuary" -> post?log("quartz_pillar","y"):rail?block(v==0?"polished_diorite":"quartz_bricks")
                    :local>=2 && local<=3?directed("cyan_glazed_terracotta","facing",local==2?(v==1 || v==4?"south":"east"):(v==1 || v==4?"west":"north"))
                    :block("calcite");
            case "service_layer" -> block(post?(rail?"iron_block":"waxed_cut_copper"):rail?"waxed_cut_copper"
                    :v<=2 && (u==5 || u==8)?((v+u)%2==0?"yellow_concrete":"black_concrete"):local==3?"iron_block":"polished_andesite");
            case "deepstone_halls" -> block(u==0 || u==7 || u==13 || v==6?"tuff_bricks":v==0?"polished_blackstone":"deepslate_bricks");
            default -> throw new IllegalArgumentException(id);
        };
    }
    /** Receives the north-west quadrant (0..7); the other three are generated by exact quarter turns. */
    private static Pattern.Material floor(String id,int x,int z) {
        int edge=Math.min(x,z); boolean inset=x>=4 && x<=5 && z>=4 && z<=5;
        return switch(id) {
            case "quiet_workshop" -> x==7 && z==7 || x==1 && z==1?log("oak_log","y")
                    :block(inset?"waxed_cut_copper":edge==1 || edge==3?"stone_bricks":"polished_andesite");
            case "arcane_archive" -> x==7 || z==7?log("dark_oak_log",x==7?"z":"x")
                    :block(edge==1?"dark_oak_planks":inset?"amethyst_block":edge==2 || x==3 || z==3?"stone_bricks":x==6 && z==6?"gilded_blackstone":"polished_deepslate");
            case "verdant_cloister" -> block(edge==1?"mud_bricks":edge==3?"stripped_birch_wood":x==7 && z>=5 || z==7 && x>=5?"green_terracotta":x==7 && z==7?"mud_bricks":"mossy_stone_bricks");
            case "astral_observatory" -> block(edge==0?"polished_blackstone":edge==1?"smooth_quartz":x==3 && z==3 || x>=6 && z>=6?"purpur_block":x+z==8 || x+z==9?"smooth_quartz":x+z>9?"polished_blackstone":"blue_terracotta");
            case "porcelain_sanctuary" -> x>=6 && z>=6?directed("cyan_glazed_terracotta","facing","north")
                    :block(x==2 && z==2?"cyan_terracotta":edge==1 || edge==4?"polished_diorite":"quartz_bricks");
            case "service_layer" -> block(x==7 && z==7 || x==1 && z==1?"iron_block":inset?"waxed_cut_copper":edge==1 || x==7 || z==7?"smooth_stone":"deepslate_tiles");
            case "deepstone_halls" -> block(edge==1?"tuff_bricks":"polished_deepslate");
            default -> throw new IllegalArgumentException(id);
        };
    }
    private static Pattern.Material ceiling(String id,int x,int z) {
        int edge=Math.min(x,z); boolean frame=edge<=1 || x==7 || z==7;
        boolean medallion=x>=3 && x<=4 && z>=3 && z<=4;
        return switch(id) {
            case "quiet_workshop" -> x==7 && z==7?block("waxed_cut_copper"):frame?log("stripped_spruce_log",x==7 || x<=1?"z":"x")
                    :medallion?log("oak_log","y"):block("stone_bricks");
            case "arcane_archive" -> frame?log("dark_oak_log",x==7 || x<=1?"z":"x")
                    :block(medallion?"purple_terracotta":x==2 || z==2 || x==5 || z==5?"gilded_blackstone":"stone_bricks");
            case "verdant_cloister" -> frame?log("stripped_oak_log",x==7 || x<=1?"z":"x"):log("stripped_birch_log","y");
            case "astral_observatory" -> block(edge==0?"polished_blackstone":edge==1 || x+z==8 || x+z==9?"smooth_quartz":x>=6 && z>=6 || x==3 && z==3?"purpur_block":"blue_terracotta");
            case "porcelain_sanctuary" -> medallion?directed("cyan_glazed_terracotta","facing",x==3?(z==3?"east":"north"):(z==3?"south":"west"))
                    :block(frame?"quartz_bricks":x==2 || z==2 || x==5 || z==5?"polished_diorite":"calcite");
            case "service_layer" -> block(x==7 && z==7 || x==1 && z==1?"iron_block":frame?"waxed_cut_copper":x==2 || z==2?"deepslate_tiles":"polished_andesite");
            case "deepstone_halls" -> block(frame?"deepslate_bricks":"tuff_bricks");
            default -> throw new IllegalArgumentException(id);
        };
    }
    private static Pattern grid(String name,int width,int height,BiFunction<Integer,Integer,Pattern.Material> material) {
        var palette=new ArrayList<Pattern.Material>(); var cells=new ArrayList<Integer>();
        for(int v=0;v<height;v++) for(int u=0;u<width;u++) {
            var value=material.apply(u,v); int index=palette.indexOf(value);
            if(index<0) { index=palette.size(); palette.add(value); } cells.add(index);
        }
        return new Pattern(name,"Elsebase",width,height,palette,cells);
    }
    private static Pattern square(String name,BiFunction<Integer,Integer,Pattern.Material> quadrant) {
        var cells=new Pattern.Material[16][16];
        for(int z=0;z<8;z++) for(int x=0;x<8;x++) {
            var value=quadrant.apply(x,z); int u=x,v=z;
            for(int turn=0;turn<4;turn++) { cells[v][u]=value; int next=15-v; v=u; u=next; value=quarterTurn(value); }
        }
        return grid(name,16,16,(u,v) -> cells[v][u]);
    }
    /** Only built-in axis/facing properties occur here; preserve directional state while rotating the grid. */
    private static Pattern.Material quarterTurn(Pattern.Material value) {
        var properties=new TreeMap<>(value.properties());
        if(properties.containsKey("axis") && !properties.get("axis").equals("y")) properties.put("axis",properties.get("axis").equals("x")?"z":"x");
        if(properties.containsKey("facing")) properties.put("facing",Objects.requireNonNull(Direction.byName(properties.get("facing"))).getClockWise().getName());
        return new Pattern.Material(value.block(),properties);
    }
    private BuiltinThemes() {}
}
